### PR TITLE
from VM

### PR DESCRIPTION
**Pull request by WaaromZoMoeilijk**

### CODE REVIEW

**Comment by WaaromZoMoeilijk** [comment]
@enoch85 Could you help me to merge this PR, static/ip.sh was already changed now I can't merge.
Tried to change the typo back to the faulty line thinking I then was able to merge but, no go.

**Comment by enoch85** [comment]
I'm busy now and don't know how to resolve conflicts yet. Sorry.

**Comment by enoch85** [comment]
Ok for this one @ezraholm50 just do a new pull OK?

**Comment by WaaromZoMoeilijk** [comment]
Was working on it, but got an error, possibly because it was re-opened at the time of creation.

**Comment by enoch85** [comment]
Sorry

**Pull request closed without merging**
